### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by shafqatsuri** [nanbingxyz/5ire#139]
**Describe the bug**
Keep getting the following message

Error
Cannot read properties of undefined (reading 'substring')

**To Reproduce**
1. Go to 'any time you ask a question'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac / Windows]
 - Version [e.g. 0.9.7]

**Additional context**

**Comment by nanbingxyz** [comment]
Could you provide a screenshot so that I can get more information.

**Comment by shafqatsuri** [comment]
<img width="1047" alt="Image" src="https://github.com/user-attachments/assets/41d9a1b0-8f56-42eb-a638-d8bac84fb851" />
Here you go. Unable to answer without even making a tool call.

**Comment by nanbingxyz** [comment]
Thanks. It seems that some enabled tools have no descriptions.  Should be fixed in next version.

**Comment by AceLeeWinnie** [comment]
This issue still can be reproduced in 0.9.8.

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/95691a1d-8403-4e9c-a3e2-ad7e4c848e6a" />

**Comment by nanbingxyz** [comment]
@AceLeeWinnie I mean next version (v0.9.9), some works still in progress.
